name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Bump versions
        run: ./bump-version.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump Version

