name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Bump versions
        run: ./Cresce.api/bump-version.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump Version

