name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2
      
      - name: Bump version
        uses: remorses/bump-version@js
        with:
            version_file: ./Cresce.Api/appsettings.json
            github_token: ${{ secrets.GITHUB_TOKEN }}
           
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump Version

