name: Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Bump versions
      run: ./bump-version.sh

    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'Cresce.Api/appsettings.json'
        prop_path: 'Version'

    - run: echo ${{steps.version.outputs.prop}}

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Bump Version
        branch: master
        tagging_message: 'v${{steps.version.outputs.prop}}'
