name: Bump-Version

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Bump versions
      run: ./bump-version.sh

    - name: get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'Cresce.Api/appsettings.json'
        prop_path: 'Version'

    - run: echo ${{steps.version.outputs.prop}}

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Bump Version
