name: .NET Core

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        
    - name: Install dependencies
      run: dotnet restore
    
    - name: edit connection string
      uses: benday-inc/edit-dbconnstr-in-appsettings@main
      with:
        pathtosettingsfile: '${{ github.workspace }}/Cresce.Api/appsettings.json'
        name: "default"
        connectionstring: "Server=cresce.cmt8hl8spkdk.eu-west-2.rds.amazonaws.com;Database=CresceDemo;User Id=${{ secrets.SQL_USER }};Password=${{ secrets.SQL_PASSWORD }};"
    
    - name: debug settings
      run: cat ${{ github.workspace }}/Cresce.Api/appsettings.json
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx 
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: contains('refs/heads/master', github.ref)
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2.1.0
      with:
        file: ./Dockerfile
        push: true
        tags: |
          alienengineer/cresce:latest
          alienengineer/cresce:1.0.0
      if: contains('refs/heads/master', github.ref)
      
    - name: Build Docker image
      uses: docker/build-push-action@v2.1.0
      with:
        file: ./Dockerfile
        push: false
        tags: |
          alienengineer/cresce:latest
          alienengineer/cresce:1.0.0
      if: contains('refs/heads/develop', github.ref)
      
    - name: Trigger Azure Deploy
      uses: muinmomin/webhook-action@v1.0.0
      with:
        url: https://$cresce:${{ secrets.AZURE_TRIGGER_TOKEN }}@cresce.scm.azurewebsites.net/docker/hook
      if: contains('refs/heads/master', github.ref)
